# Generated by Django 4.1.2 on 2022-11-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=10)),
                ('dahil1', models.CharField(max_length=50)),
                ('dahil2', models.CharField(max_length=50)),
                ('dahil3', models.CharField(max_length=50)),
                ('dahil4', models.CharField(max_length=50)),
                ('dahil5', models.CharField(max_length=50)),
                ('dahil6', models.CharField(max_length=50)),
                ('dahil7', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=models.CharField(max_length=10))),
            ],
        ),
    ]
