# Generated by Django 4.1.2 on 2022-12-27 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Course_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Course_title', models.CharField(max_length=30)),
                ('Course_Descp', models.CharField(max_length=250)),
                ('Course_Img', models.ImageField(blank=True, null=True, upload_to='course')),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_title', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('dahil1', models.CharField(max_length=50)),
                ('dahil2', models.CharField(max_length=50)),
                ('dahil3', models.CharField(max_length=50)),
                ('dahil4', models.CharField(max_length=50)),
                ('dahil5', models.CharField(max_length=50)),
                ('dahil6', models.CharField(max_length=50)),
                ('dahil7', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_message', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=20)),
                ('LastName', models.CharField(blank=True, max_length=20)),
                ('SignDate', models.DateField(auto_now_add=True)),
                ('Person_Img', models.ImageField(blank=True, default='profile1.png', null=True, upload_to='person')),
                ('price_ID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='ln.prices')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('Enrolment_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ln.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('Instructor_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='price_ID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='ln.prices'),
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('Blog_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Blog_Title', models.CharField(max_length=50)),
                ('Blog_Descp', models.CharField(max_length=250)),
                ('Blog_Date', models.DateField(auto_now_add=True)),
                ('Blog_Img', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
