# Generated by Django 4.1.2 on 2022-11-15 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ln', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Course_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Course_title', models.CharField(max_length=30)),
                ('Course_Descp', models.CharField(max_length=250)),
                ('Course_Img', models.ImageField(blank=True, null=True, upload_to='course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('Instructor_ID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('Enrolment_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ln.course')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('Person_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('SignDate', models.DateField(auto_now_add=True)),
                ('Person_Img', models.ImageField(blank=True, null=True, upload_to='person')),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('price_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('price_title', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=10)),
                ('dahil1', models.CharField(max_length=50)),
                ('dahil2', models.CharField(max_length=50)),
                ('dahil3', models.CharField(max_length=50)),
                ('dahil4', models.CharField(max_length=50)),
                ('dahil5', models.CharField(max_length=50)),
                ('dahil6', models.CharField(max_length=50)),
                ('dahil7', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=models.CharField(max_length=10))),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Person_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ln.person')),
                ('price_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ln.prices')),
            ],
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.AddField(
            model_name='enrolment',
            name='Student_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ln.student'),
        ),
        migrations.AddField(
            model_name='courseinstructor',
            name='Person_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ln.person'),
        ),
        migrations.AddField(
            model_name='course',
            name='Instructor_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ln.courseinstructor'),
        ),
    ]
