# Generated by Django 4.1.2 on 2023-01-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ln', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='dahil4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prices',
            name='dahil5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prices',
            name='dahil6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prices',
            name='dahil7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
