# Generated by Django 4.1.2 on 2022-11-15 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ln', '0002_course_courseinstructor_enrolment_person_prices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='image',
        ),
    ]
