# Generated by Django 4.1.2 on 2022-11-29 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ln', '0003_remove_prices_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('Blog_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Blog_Title', models.CharField(max_length=50)),
                ('Blog_Descp', models.CharField(max_length=250)),
                ('Blog_Date', models.DateField(auto_now_add=True)),
                ('Instructor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ln.courseinstructor')),
            ],
        ),
    ]
