# Generated by Django 4.1.2 on 2022-11-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ln', '0004_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Blog_Img',
            field=models.ImageField(blank=True, null=True, upload_to='blog'),
        ),
    ]
